# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
# https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables

name: Push Workflow

on:
  push:

env:
  # This set implicitly by GitHub, but I rather be explicit about it.
  CI: true

jobs:
  ci-cd:
    name: ci-cd

    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}

    runs-on: ubuntu-latest

    env:
      npm_config_cache: $HOME/.npm
      npm_cache_key: build-node-modules-cache

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Determine Node.js version to use
        run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvm

      # https://github.com/actions/setup-node
      - name: Setup Node.js ${{ steps.nvm.outputs.version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvm.outputs.version }}

      # https://github.com/actions/cache
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ${{ env.npm_config_cache }}
          key: ${{ env.npm_cache_key }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ env.npm_cache_key }}-

      - name: install
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm test

      - name: build
        run: npm run build

      # https://github.com/codecov/codecov-action
      - name: Collect coverage report
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info
          # env_vars: OS,PYTHON
          name: "@abstracter/winston-logger"
          fail_ci_if_error: true

      - name: Release
        env:
          GIT_AUTHOR_NAME: ${{ secrets.BOT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.BOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.BOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.BOT_EMAIL }}

          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_EMAIL: ${{ secrets.BOT_EMAIL }}
          NPM_USERNAME: ${{ secrets.BOT_NAME }}

          GITHUB_TOKEN: ${{ secrets.BOT_PUSH_PAT }}
        run: npm run release
